name: BetterPortals
version: 1.1.0
main: org.envel.betterportals.bukkit.BetterPortals
description: "Plugin which allows nether portals to be seen through, and allows custom portal creation"
folia-supported: true
author: Envel
depend:
  - ProtocolLib
api-version: "1.21"
softdepend:
  - Multiverse-Core
  - My_Worlds
  - Vault
commands:
  betterportals:
    description: Main plugin command
    aliases:
      - bp
permissions:
  betterportals.createfromcoords:
    description: ' Allows you to use /bp createfromcoords'
    default: op
  betterportals.getname:
    description: ' Allows you to use /bp getname'
    default: op
  betterportals.link:
    description: ' Allows you to create portals with /bp link'
    default: op
  betterportals.linkexternal:
    description: ' Allows you to run /bp linkexternal to create cross-server portals.'
    default: op
  betterportals.removeclosest:
    description: ' Allows you to use /bp removeclosest'
    default: op
  betterportals.reload:
    description: ' Allows you to use /bp reload'
    default: op
  betterportals.create:
    description: ' Allows you to use /bp create'
    default: op
  betterportals.updatecoords:
    description: ' Allows you to use /bp updatecoords'
    default: op
  betterportals.tp:
    description: ' Allows you to use /bp tp'
    default: op
  betterportals.setprice:
    description: ' Allows you to use /bp setprice'
    default: op
  betterportals.setpreset:
    description: ' Allows you to use /bp setpreset'
    default: op
  betterportals.bypassprice:
    description: ' Allows you to bypass paying for custom portals.'
    default: op
  betterportals.admin:
    description: ' Allows you to bypass portal size restrictions, and see debug information.'
    default: op
  betterportals.createcustom:
    description: ' Allows you to use /bp createcustom'
    default: op
  betterportals.wand:
    description: ' Allows you to use /bp wand'
    default: op
  betterportals.user:
    description: ' Allows you to use portals'
    default: true
  betterportals.see:
    description: ' Allows you to see through portals'
    default: true
